version: "3.9"

services:
  backend:
    build:
      context: ./api
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py collectstatic --no-input
             exec gunicorn --bind 0.0.0.0:8000 api.wsgi:application -w 2"

  frontend:
    build:
      context: ./frontend
    volumes:
      - front_build:/frontend/build

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - front_build:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  front_build:
